CREATE DATABASE LOGIN;

CREATE TABLE SESION( 
IDUsuario CHAR(20), 
CONTRA VARCHAR(20),
NOMB VARCHAR(50),
APELL VARCHAR(50),
RANGO INT
);
INSERT INTO SESION (IDUsuario, CONTRA, NOMB, APELL, RANGO) VALUES ('NiltonDirector', 'nilton123','Nilton','Tolentino',1); 
INSERT INTO SESION (IDUsuario, CONTRA, NOMB, APELL, RANGO) VALUES ('NiltonProfesor', 'nilton1234','Nilton1','Tolentino1',2); 
INSERT INTO SESION (IDUsuario, CONTRA, NOMB, APELL, RANGO) VALUES ('NiltonAlumno', 'nilton12345','Nilton2','Tolentino3',3);
INSERT INTO SESION (IDUsuario, CONTRA) VALUES ('Carlo', 'carlo123');
SELECT * FROM SESION;